### ISSUE TITLE
runnint init_db on initialized db exits with error

### ISSUE THREAD

**Issue by spinus** [aartur/mschematool#1]
I'm using automated scripts on dev/test/prod environments. To avoid manual detection of installed migrations table would be nice if that would be integrated into init_db command. Than I can run init_db multiple times without writing a lot of boilerplate code to check it was already installed.

For example "CREATE TABLE IF NOT EXISTS"?

**Comment by aartur** [comment]
That's a good idea, I've implemented it. Do you need a new PyPI release to use this?

**Comment by spinus** [comment]
Wow, that was quick :-) Thank you. 

Would be nice to have a PyPI package. If you have time to release over next week this would be great, no rush.

**Comment by aartur** [comment]
Version 0.6.3 is released with the init_db change.

**Comment by spinus** [comment]
Nice, thank you.
