### ISSUE TITLE
0.6.3 release is broken

### ISSUE THREAD

**Issue by spinus** [aartur/mschematool#2]
I downloaded 0.6.3 from PyPI and I had some errors so I switched back to previous version but now I had few minutes to look closer. The 0.6.3 package on PyPI is broken. Executors directory is missing.

In setup.py you have to specify directly all packages (and subpackages) or use find_packages function from setuptools.

**Comment by spinus** [comment]
Please check #3

**Comment by aartur** [comment]
Thanks for the fixes, version 0.6.4 contains them.

There are tests but they run code from a local clone, and I only tested basic behaviour after installing 0.6.3 from PyPI...
