### ISSUE TITLE
Postgresql DLL function create script error

### ISSUE THREAD

**Issue by blasferna** [aartur/mschematool#7]
> psycopg2.ProgrammingError: una cadena separada por $ está inconclusa en o cerca de «$BODY$
> DECLARE
>    V_CLAVE NUMERIC»
> LINE 2:   RETURNS numeric AS $BODY$

return this error when try to execute **create function** migration

**Comment by CrescentFresh** [comment]
Possibly better said in issue #8

**Comment by aartur** [comment]
Ok, so I'm closing it as it's better described in #8.
