### ISSUE TITLE
Add support for dollar-quoted strings

### ISSUE THREAD

**Issue by CrescentFresh** [aartur/mschematool#8]
Standard practice when defining PL/pgSQL functions (or any language supported by your postgresql installation) is to use [dollar-quoted strings](https://www.postgresql.org/docs/9.0/static/sql-syntax-lexical.html) around the function body, for example: 

    CREATE OR REPLACE FUNCTION random_number() RETURNS INT AS $$
    BEGIN
      RETURN 42;
    END;
    $$ LANGUAGE plpgsql;

The body of the function is surrounded by `$$`. When the above is a migration, mschema tool results in an error:

_psycopg2.ProgrammingError: unterminated dollar-quoted string at or near "$$_

mschematool only supports/recognizes function bodies surrounded by single quotes (as is the old way of defining any string constant). So to get around the above error mschematool forces the author to write the function definition like this:

    CREATE OR REPLACE FUNCTION random_number() RETURNS INT AS 
    '
    BEGIN
      RETURN 42;
    END;
    ' LANGUAGE plpgsql;

The problem is in the implementation of [`_sqlfile_to_statements`](https://github.com/aartur/mschematool/blob/v0.6.5/mschematool/core.py#L93) which uses a regular expression to split on semicolons, hoping to yield a series of executable sql statements. This is the wrong way to parse for sql statements.

As a suggestion, a library like [sqlparse](https://github.com/andialbrecht/sqlparse) could be utilized instead to properly recognize the function definition as a whole, complete statement (or any use of dollar-quoted strings for that matter).

**Comment by blasferna** [comment]
The solution works very well only it is uncomfortable if you want to include something like that in the body of the routine:

`to_date ('02/02/2018','DD/MM/YYYY')`

Since it is necessary to add more than one quote, example:

`to_date (''02/02/2018'', '' DD/MM/YYYY''))`

But that is a simple detail. Thanks!!!

**Comment by CrescentFresh** [comment]
It is very uncomfortable to use your words. I don't want to re-train the team on how to define function bodies just because our migration tool doesn't understand dollar-quotes.

Honestly we didn't even realize `$$` was just a delimiter, we thought it was *the* way to define bodies, like `{` and `}` in other languages.

**Comment by blasferna** [comment]
I understand your concern perfectly. In my case it's simple because I work alone, but being in a development team changes. I agree that the tool should support the dollar-quoted strings, as I managed to solve that way I thought it was just a detail, I guess I was not thinking at all.

**Comment by aartur** [comment]
Sorry for the delay - for some reason I didn't receive notifications from GitHub.

The original function `_sqlfile_to_statements` was taken from `south` migrations, so I assumed it's pretty robust. For sure using `sqlparse` is a better option.

I merged the pull request and made the 0.8 release. I made the `sqlparse` a global dependency so it'll work with Sqlite3.

**Comment by CrescentFresh** [comment]
Awesome!

So will `pip install mchematool` pick this fix up? How do you get things into the pip repo? (I'm not too familiar with python internals).

**Comment by aartur** [comment]
> So will pip install mchematool pick this fix up?

Yes. You can use `pip install --upgrade mschematool` to make sure it doesn't use a cached old version.

> How do you get things into the pip repo? (I'm not too familiar with python internals).

There's plenty of tutorials, see e.g. https://python-packaging.readthedocs.io/en/latest/

**Comment by CrescentFresh** [comment]
Nice!

Are you going to tag a 0.8 release in github? The lack of a 0.8 version here led our devs to believe it still wasn't released to pip yet. Might confuse others.

**Comment by aartur** [comment]
Ok, done.
